### ISSUE TITLE
ON_OFF fixture "dims" when it should not

### ISSUE THREAD

**Issue by JosephEHerbst** [RevolutionLighting/rpdg_svc#10]
{
	"id": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
	"name": "Dimmer change with no dim setting",
	"description": "Set configuration to create a fixture that has \"Don't Dim\" set and if the dimmer is set to 0 the fixture goes off (0%) and if it is >0 then it goes to 100%\nTry to Dim a fixture that has Dont Dim Set for Inputs 1-4 on output 1 only",
	"order": [
		"fa0e0815-ee5a-fa90-318c-82ebcd773253",
		"ee2cabe7-01f5-4796-804d-55ef6aa4e6e7",
		"778fbbf6-c7c7-64ce-189d-b2bbfe29dd88",
		"af46ed5d-268a-435e-a860-1a2887033210",
		"43dfeaa6-e8ab-c7af-d38f-f8031b626ae0",
		"2a1ff4ef-b796-4176-a16c-c82d76f5da17",
		"6a23dc51-7958-b6a5-56ec-8c26629c1719",
		"98e3e543-eaef-5ceb-979d-4c190d04d5bc"
	],
	"folders": [],
	"timestamp": 1483302367379,
	"owner": "1406179",
	"public": false,
	"requests": [
		{
			"id": "2a1ff4ef-b796-4176-a16c-c82d76f5da17",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\ntests[\"Response time is less than 200ms\"] = responseTime < 200;\nvar jsonData = JSON.parse(responseBody);\ntests[\"Value of pwm output 1 is correct\"] = jsonData == 100;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483308560780,
			"name": "getDimmerLevel_5V",
			"description": "and verify it is 5V",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n  \"uid\": \"192_168_1_100_1\"\n}"
		},
		{
			"id": "43dfeaa6-e8ab-c7af-d38f-f8031b626ae0",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/settestdimmerlevel",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\ntests[\"Response time is less than 200ms\"] = responseTime < 200;\n",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483305273855,
			"name": "setDimmerLevel_5V",
			"description": "set dimmer to 5V and make sure output stays at 100",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n  \"inputnumber\": \"1\",\n  \"levelvolts\": \"5\"\n}"
		},
		{
			"id": "6a23dc51-7958-b6a5-56ec-8c26629c1719",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/getfixturelevel",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\ntests[\"Response time is less than 200ms\"] = responseTime < 200;\nvar jsonData = JSON.parse(responseBody);\ntests[\"Value of pwm output 1 is correct\"] = jsonData == 100;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483308320720,
			"name": "getFixtureLevel_for_output_1",
			"description": "and verify it is 100%",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n  \"uid\": \"192_168_1_100_1\"\n}"
		},
		{
			"id": "778fbbf6-c7c7-64ce-189d-b2bbfe29dd88",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/setfixturelevel",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\ntests[\"Response time is less than 200ms\"] = responseTime < 200;\nvar jsonData = JSON.parse(responseBody);\ntests[\"Value of pwm output 0 is correct\"] = jsonData[0] == 100;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483305086397,
			"name": "set Toggle Fixture to ON",
			"description": "",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n  \"request\": \"wall\",\n  \"uid\": \"192_168_1_100_1\",\n  \"on_off\": {\n  \t\"levelpct\": \"100\"\n  }\n}"
		},
		{
			"id": "98e3e543-eaef-5ceb-979d-4c190d04d5bc",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/cleartestmode",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483308600600,
			"name": "Clear Test Mode",
			"description": "",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": ""
		},
		{
			"id": "af46ed5d-268a-435e-a860-1a2887033210",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/getfixturelevel",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n\ntests[\"Response time is less than 200ms\"] = responseTime < 200;\nvar jsonData = JSON.parse(responseBody);\ntests[\"Value of pwm output 1 is correct\"] = jsonData == 100;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483308327890,
			"name": "getFixtureLevel_for_output_1",
			"description": "and verify it is 100%",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n  \"uid\": \"192_168_1_100_1\"\n}"
		},
		{
			"id": "ee2cabe7-01f5-4796-804d-55ef6aa4e6e7",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/setconfig",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;\n",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483304139699,
			"name": "SetConfig_One_Fixture_No_Dim",
			"description": "",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": "{\n    \"fixtures\": [\n        {\n            \"assignment\": [1],\n            \"name\": \"TEST_FIX_NoDim\",\n            \"uid\": \"192_168_1_100_1\",\n            \"type\": \"on_off\",\n            \"globalgroups\": 0,\n            \"localgroups\": \"\",\n            \"status\": 0,\n            \"zero2teninputs\": [1],\n            \"contactinputs\": [],\n            \"parameters\": {\n                \"dimoptions\": \"0\",\n                \"dimrate\": \"0\",\n                \"brightenrate\": \"0\",\n                \"resptoocc\": \"-1\",\n                \"resptovac\": \"0\",\n                \"resptodl50\": \"0\",\n                \"resptodl40\": \"10\",\n                \"resptodl30\": \"25\",\n                \"resptodl20\": \"50\",\n                \"resptodl10\": \"75\",\n                \"resptodl0\": \"100\",\n                \"daylightceiling\": \"100\",\n                \"manualceiling\": \"100\",\n                \"daylightfloor\": \"0\",\n                \"manualfloor\": \"0\"\n            }\n        }\n    ],\n    \"inputcfg\": {\n        \"zero2ten\": [\n            \"wall\",\n            \"wall\",\n            \"wall\",\n            \"wall\"\n        ],\n        \"contact\": [\n            \"dry\",\n            \"dry\",\n            \"diss\",\n            \"diss\"\n        ]\n    },\n    \"outputcfg\": [\n        {\n            \"enable\": true,\n            \"resp_sched\": false,\n            \"resp_occ\": false,\n            \"resp_wall\": false,\n            \"always_on\": true\n        },\n        {\n            \"enable\": true,\n            \"resp_sched\": false,\n            \"resp_occ\": false,\n            \"resp_wall\": false,\n            \"always_on\": true\n        },\n        {\n            \"enable\": true,\n            \"resp_sched\": false,\n            \"resp_occ\": false,\n            \"resp_wall\": false,\n            \"always_on\": true\n        },\n        {\n            \"enable\": true,\n            \"resp_sched\": false,\n            \"resp_occ\": false,\n            \"resp_wall\": false,\n            \"always_on\": true\n        }\n    ]\n}"
		},
		{
			"id": "fa0e0815-ee5a-fa90-318c-82ebcd773253",
			"headers": "Content-Type: application/json\n",
			"url": "http://localhost:3000/settestmode",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [],
			"dataMode": "raw",
			"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;",
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1483304137393,
			"name": "Set Test Mode",
			"description": "",
			"collectionId": "98166f7d-ec05-5ff0-dfa1-20e3c7f3e0bb",
			"responses": [],
			"rawModeData": ""
		}
	]
}

**Comment by npreiser** [comment]
Not making sense,  can you just quickly describe whats going on.  I checked on_off just today, and it appears to work for me.

**Comment by npreiser** [comment]
this one should be solved as of 1/2/17

**Comment by JosephEHerbst** [comment]
I can not get the test to run - settestmode breaks

Closed out several bugs and opened some new ones (normal mode (web browser
- not test mode)

**Comment by JosephEHerbst** [comment]
confirmed fixed
