### ISSUE TITLE
sliders respond to touch but not to mouse

### ISSUE THREAD

**Issue by JosephEHerbst** [RevolutionLighting/rpdg_svc#14]
I can change the sliders only with my finger - mouse events do not work

**Comment by npreiser** [comment]
do you mean that when you click in the slider and the slider jumps to the mouse point,  it does not send anything ?,  not following .

**Comment by JosephEHerbst** [comment]
My mouse click or drag do nothing 
Only my finger on the touchscreen moves the slider

Joe Herbst
503.475.1336

**Comment by npreiser** [comment]
Im playing with the sliders now,  and they suck,  something is not right,  
it works if you drag,  but that is it,  clicking is not working correctly,  I may have to change the 
control  , ,,,Again !!!

**Comment by JosephEHerbst** [comment]
Sorry dude....
Anything I can do?

Joe Herbst
503.475.1336

**Comment by npreiser** [comment]
OK,  pull again and let me know,  I solved the issues I was seeing,  not sure but it probably was related

close this if fixed.  
if you are still having issue call me so I can get detail on whats happening,

**Comment by JosephEHerbst** [comment]
fixed and verrified

**Comment by JosephEHerbst** [comment]
nice - fixed
All the bugs are clear!
I'll try to catch some more later - I am bringing Dan in so we are now 2:1
:-)

Nice work getting all that to come together
