### ISSUE TITLE
style feature request

### ISSUE THREAD

**Issue by JosephEHerbst** [RevolutionLighting/rpdg_svc#2]
Change style of 24V outputs to be the same as inputs.....disabled, Respond to ..., Always ON are excluseve

![image](https://cloud.githubusercontent.com/assets/23506488/21459508/a1fda8ae-c8f3-11e6-9711-d487a0e0c422.png)
![capture](https://cloud.githubusercontent.com/assets/23506488/21459526/b8680878-c8f3-11e6-8cc1-c01384d81099.PNG)

**Comment by npreiser** [comment]
fixed 1/2/17,
