### ISSUE TITLE
Integrate into object definition....

### ISSUE THREAD

**Issue by JosephEHerbst** [RevolutionLighting/rpdg_svc#3]
Status Page (power and dim levels) - Power is sum of channels;  dim level on CCT is sum of two channels
Override Page (zone sliders now become a pair or quadlet of sliders.)
Scenes Page (parameters of fixture stored as part of scene....ex CCT and intensity, Color/Brightness (white level) and intensity.

**Comment by npreiser** [comment]
in progress,  status page completed, and override section completed,

**Comment by JosephEHerbst** [comment]
verified working
